version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    target-branch: main
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: main
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    target-branch: main

