run:
  timeout: 10m

linters:
  enable:
    # Enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Disabled by default
    - asasalint
    - asciicheck
    - bodyclose
    - errorlint
    - gci
    - gocyclo
    - gosec
    - makezero
    - noctx
    - paralleltest
    - prealloc
    - reassign
    - revive
    - whitespace
    - wsl

issues:
  max-issues-per-linter: 0 # Unlimited
  max-same-issues: 0 # Unlimited
