environment: development

database:
  driver: cockroachdb
  partition: true
  uri: postgres://root@localhost:26257/defaultdb

redis:
  uri: redis://localhost:6379/0

rss3_chain:
  endpoint_l1: https://rpc.ankr.com/eth_sepolia
  endpoint_l2: https://rpc.testnet.rss3.io
  block_threads_l1: 20
  block_threads_l2: 100

settler:
  private_key:
  wallet_address:
  signer_endpoint: http://localhost:3000
  epoch_interval_in_hours: 18
  gas_limit: 3000000
  batch_size: 200

active_scores:
  gini_coefficient: 2
  staker_factor: 0.05
  epoch_limit: 10
  node_threshold: 0.4

geo_ip:
  account:
  license_key:

rpc:
  network:
    ethereum:
      endpoint: https://rpc.ankr.com/eth
    crossbell:
      endpoint: https://rpc.crossbell.io
    polygon:
      endpoint: https://rpc.ankr.com/polygon
    farcaster:
      endpoint: https://nemes.farcaster.xyz:2281
      api_key:

telemetry:
  endpoint: localhost:4318
  insecure: true

distributor:
  max_demotion_count: -1
  qualified_node_count: 3
  verification_count: 3
  tolerance_seconds: 1200

