-- +goose Up
-- +goose StatementBegin
CREATE TABLE "stake"."cumulative_earning_snapshots"
(
    "id"                 bigint GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 MINVALUE 0 START 0),
    "date"               timestamptz NOT NULL,
    "epoch_id"           bigint      NOT NULL,
    "owner_address"      bytea       NOT NULL,
    "total_staking_cumulative_earnings"  decimal     NOT NULL,
    "created_at"         timestamptz NOT NULL DEFAULT now(),
    "updated_at"         timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT "pkey" PRIMARY KEY ("owner_address", "epoch_id")
);

CREATE INDEX "cumulative_earning_snapshots_date_idx" ON "stake"."cumulative_earning_snapshots" ("date");
CREATE INDEX "cumulative_earning_snapshots_epoch_id_idx" ON "stake"."cumulative_earning_snapshots" ("epoch_id" DESC);
CREATE INDEX "cumulative_earning_snapshots_id_idx" ON "stake"."cumulative_earning_snapshots" ("id" DESC);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE "stake"."cumulative_earning_snapshots";
-- +goose StatementEnd
