-- +goose Up
-- +goose StatementBegin
ALTER TABLE "node"."snapshots"
    rename to "count_snapshots";

CREATE TABLE "node"."min_tokens_to_stake_snapshots"
(
    "id"                  bigint GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 MINVALUE 0 START 0),
    "date"                timestamptz NOT NULL,
    "epoch_id"            bigint      NOT NULL,
    "node_address"        bytea       NOT NULL,
    "min_tokens_to_stake" decimal     NOT NULL,
    "created_at"          timestamptz NOT NULL DEFAULT now(),
    "updated_at"          timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT "pkey" PRIMARY KEY ("node_address", "epoch_id")
);

CREATE INDEX "min_tokens_to_stake_snapshots_date_idx" ON "node"."min_tokens_to_stake_snapshots" ("date");
CREATE INDEX "min_tokens_to_stake_snapshots_epoch_id_idx" ON "node"."min_tokens_to_stake_snapshots" ("epoch_id" DESC, "id" DESC);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE "node"."count_snapshots"
    rename to "snapshots";

DROP TABLE "node"."min_tokens_to_stake_snapshots";
-- +goose StatementEnd
