-- +goose Up
-- +goose StatementBegin
ALTER TABLE "stake"."snapshots"
    rename to "count_snapshots";

CREATE INDEX idx_block_number
    ON "stake"."chips" ("block_number");

CREATE TABLE "stake"."profit_snapshots"
(
    "id"                 bigint GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 MINVALUE 0 START 0),
    "date"               timestamptz NOT NULL,
    "epoch_id"           bigint      NOT NULL,
    "owner_address"      bytea       NOT NULL,
    "total_chip_amounts" decimal     NOT NULL,
    "total_chip_values"  decimal     NOT NULL,
    "created_at"         timestamptz NOT NULL DEFAULT now(),
    "updated_at"         timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT "pkey" PRIMARY KEY ("owner_address", "epoch_id")
);

CREATE INDEX "profit_snapshots_date_idx" ON "stake"."profit_snapshots" ("date");
CREATE INDEX "profit_snapshots_epoch_id_idx" ON "stake"."profit_snapshots" ("epoch_id" DESC, "id" DESC);
CREATE INDEX "profit_snapshots_total_chip_amounts_idx" ON "stake"."profit_snapshots" ("total_chip_amounts" DESC);
CREATE INDEX "profit_snapshots_total_chip_values_idx" ON "stake"."profit_snapshots" ("total_chip_values" DESC);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE "stake"."count_snapshots"
    rename to "snapshots";

DROP TABLE "stake"."profit_snapshots";
-- +goose StatementEnd
