-- +goose Up
-- +goose StatementBegin
CREATE TABLE "node"."apy_snapshots"
(
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 MINVALUE 0 START 0),
    "date"         timestamptz NOT NULL,
    "epoch_id"     bigint      NOT NULL,
    "node_address" bytea       NOT NULL,
    "apy"          decimal     NOT NULL,
    "created_at"   timestamptz NOT NULL DEFAULT now(),
    "updated_at"   timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT "pkey" PRIMARY KEY ("node_address", "epoch_id")
);

CREATE INDEX "apy_snapshots_date_idx" ON "node"."apy_snapshots" ("date");
CREATE INDEX "apy_snapshots_epoch_id_idx" ON "node"."apy_snapshots" ("epoch_id" DESC, "id" DESC);

CREATE SCHEMA "epoch";

CREATE TABLE "epoch"."apy_snapshots"
(
    "epoch_id"   bigint      NOT NULL,
    "date"       timestamptz NOT NULL,
    "apy"        decimal     NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT "pkey" PRIMARY KEY ("epoch_id")
);

CREATE INDEX "apy_snapshots_date_idx" ON "epoch"."apy_snapshots" ("date");


-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE "node"."apy_snapshots";
DROP TABLE "epoch"."apy_snapshots";
-- +goose StatementEnd
