-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS "node_invalid_response"
(
    "id"                 bigint      GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 MINVALUE 0 START 0),
    "epoch_id"           bigint      NOT NULL,
    "status"             TEXT        NOT NULL,
    "validator_node"     bytea       NOT NULL,
    "validator_request"  TEXT        NOT NULL,
    "validator_response" json        NOT NULL,
    "verified_node"      bytea       NOT NULL,
    "verified_request"   TEXT        NOT NULL,
    "verified_response"  json        NOT NULL,
    "created_at"         timestamptz NOT NULL DEFAULT now(),
    "updated_at"         timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT "pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_epoch_id" ON "node_invalid_response" ("epoch_id" DESC);
CREATE INDEX IF NOT EXISTS "idx_validator_node" ON "node_invalid_response" ("validator_node");
CREATE INDEX IF NOT EXISTS "idx_verified_node" ON "node_invalid_response" ("verified_node");
CREATE INDEX IF NOT EXISTS "idx_status" ON "node_invalid_response" ("status", "created_at" DESC);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE "node_invalid_response";
-- +goose StatementEnd
