-- +goose Up
-- +goose StatementBegin
DROP TABLE IF EXISTS "node"."min_tokens_to_stake_snapshots";

ALTER TABLE "public"."node_info"
    DROP COLUMN "min_tokens_to_stake";
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
CREATE TABLE "node"."min_tokens_to_stake_snapshots"
(
    "id"                  bigint GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 MINVALUE 0 START 0),
    "date"                timestamptz NOT NULL,
    "epoch_id"            bigint      NOT NULL,
    "node_address"        bytea       NOT NULL,
    "min_tokens_to_stake" decimal     NOT NULL,
    "created_at"          timestamptz NOT NULL DEFAULT now(),
    "updated_at"          timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT "pkey" PRIMARY KEY ("node_address", "epoch_id")
);

CREATE INDEX "min_tokens_to_stake_snapshots_date_idx" ON "node"."min_tokens_to_stake_snapshots" ("date");
CREATE INDEX "min_tokens_to_stake_snapshots_epoch_id_idx" ON "node"."min_tokens_to_stake_snapshots" ("epoch_id" DESC, "id" DESC);

ALTER TABLE "public"."node_info"
    ADD "min_tokens_to_stake" decimal;
-- +goose StatementEnd