// Code generated by "enumer --values --type=NodeStatus --linecomment --output node_status_string.go --json --yaml --sql"; DO NOT EDIT.

package schema

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _NodeStatusName = "noneregisteredinitializingoutdatedonlineofflineslashingslashedexitingexited"

var _NodeStatusIndex = [...]uint8{0, 4, 14, 26, 34, 40, 47, 55, 62, 69, 75}

const _NodeStatusLowerName = "noneregisteredinitializingoutdatedonlineofflineslashingslashedexitingexited"

func (i NodeStatus) String() string {
	if i < 0 || i >= NodeStatus(len(_NodeStatusIndex)-1) {
		return fmt.Sprintf("NodeStatus(%d)", i)
	}
	return _NodeStatusName[_NodeStatusIndex[i]:_NodeStatusIndex[i+1]]
}

func (NodeStatus) Values() []string {
	return NodeStatusStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _NodeStatusNoOp() {
	var x [1]struct{}
	_ = x[NodeStatusNone-(0)]
	_ = x[NodeStatusRegistered-(1)]
	_ = x[NodeStatusInitializing-(2)]
	_ = x[NodeStatusOutdated-(3)]
	_ = x[NodeStatusOnline-(4)]
	_ = x[NodeStatusOffline-(5)]
	_ = x[NodeStatusSlashing-(6)]
	_ = x[NodeStatusSlashed-(7)]
	_ = x[NodeStatusExiting-(8)]
	_ = x[NodeStatusExited-(9)]
}

var _NodeStatusValues = []NodeStatus{NodeStatusNone, NodeStatusRegistered, NodeStatusInitializing, NodeStatusOutdated, NodeStatusOnline, NodeStatusOffline, NodeStatusSlashing, NodeStatusSlashed, NodeStatusExiting, NodeStatusExited}

var _NodeStatusNameToValueMap = map[string]NodeStatus{
	_NodeStatusName[0:4]:        NodeStatusNone,
	_NodeStatusLowerName[0:4]:   NodeStatusNone,
	_NodeStatusName[4:14]:       NodeStatusRegistered,
	_NodeStatusLowerName[4:14]:  NodeStatusRegistered,
	_NodeStatusName[14:26]:      NodeStatusInitializing,
	_NodeStatusLowerName[14:26]: NodeStatusInitializing,
	_NodeStatusName[26:34]:      NodeStatusOutdated,
	_NodeStatusLowerName[26:34]: NodeStatusOutdated,
	_NodeStatusName[34:40]:      NodeStatusOnline,
	_NodeStatusLowerName[34:40]: NodeStatusOnline,
	_NodeStatusName[40:47]:      NodeStatusOffline,
	_NodeStatusLowerName[40:47]: NodeStatusOffline,
	_NodeStatusName[47:55]:      NodeStatusSlashing,
	_NodeStatusLowerName[47:55]: NodeStatusSlashing,
	_NodeStatusName[55:62]:      NodeStatusSlashed,
	_NodeStatusLowerName[55:62]: NodeStatusSlashed,
	_NodeStatusName[62:69]:      NodeStatusExiting,
	_NodeStatusLowerName[62:69]: NodeStatusExiting,
	_NodeStatusName[69:75]:      NodeStatusExited,
	_NodeStatusLowerName[69:75]: NodeStatusExited,
}

var _NodeStatusNames = []string{
	_NodeStatusName[0:4],
	_NodeStatusName[4:14],
	_NodeStatusName[14:26],
	_NodeStatusName[26:34],
	_NodeStatusName[34:40],
	_NodeStatusName[40:47],
	_NodeStatusName[47:55],
	_NodeStatusName[55:62],
	_NodeStatusName[62:69],
	_NodeStatusName[69:75],
}

// NodeStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func NodeStatusString(s string) (NodeStatus, error) {
	if val, ok := _NodeStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _NodeStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to NodeStatus values", s)
}

// NodeStatusValues returns all values of the enum
func NodeStatusValues() []NodeStatus {
	return _NodeStatusValues
}

// NodeStatusStrings returns a slice of all String values of the enum
func NodeStatusStrings() []string {
	strs := make([]string, len(_NodeStatusNames))
	copy(strs, _NodeStatusNames)
	return strs
}

// IsANodeStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i NodeStatus) IsANodeStatus() bool {
	for _, v := range _NodeStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for NodeStatus
func (i NodeStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for NodeStatus
func (i *NodeStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("NodeStatus should be a string, got %s", data)
	}

	var err error
	*i, err = NodeStatusString(s)
	return err
}

// MarshalYAML implements a YAML Marshaler for NodeStatus
func (i NodeStatus) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for NodeStatus
func (i *NodeStatus) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = NodeStatusString(s)
	return err
}

func (i NodeStatus) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *NodeStatus) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of NodeStatus: %[1]T(%[1]v)", value)
	}

	val, err := NodeStatusString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
