name: Build and Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - "deploy/**"
  pull_request:
    paths-ignore:
      - "deploy/**"
jobs:
  build:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/docker-tpl.yaml@main
    with:
      images: rss3/global-indexer
      context: .
      dockerfile: ./Dockerfile
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
