name: Test
on:
  push:
    branches:
      - main
    paths-ignore:
      - "deploy/**"
  pull_request:
    paths-ignore:
      - "deploy/**"

jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
#      - name: Import Secrets
#        uses: hashicorp/vault-action@v2.4.0
#        with:
#          url: ${{ secrets.VAULT_ADDR }}
#          token: ${{ secrets.VAULT_TOKEN }}
#          secrets: |
#            kv/data/network/rss3-node ENDPOINT_ETHEREUM ;
#            kv/data/network/rss3-node ENDPOINT_POLYGON ;
#            kv/data/network/rss3-node FARCASTER_URI
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: make test